### ISSUE TITLE
Capitalization doesn't seem present in the dictionary

### ISSUE THREAD

**Issue by Georift** [EPLHREU/emily-symbols#13]
Capitalization doesn't seem present in the dictionary. The docs have the following:

![image](https://user-images.githubusercontent.com/859430/173883111-5b2e7538-474e-430e-93c7-d72e970171b6.png)

But I can't seem to see any reference to it in the dictionary. I might be miss understanding how this script works, I'm fairly new to Plover.

**Comment by Georift** [comment]
It definitely exists in the code, https://github.com/EPLHREU/emily-symbols/blob/main/emily-symbols.py#L24

I'm not sure sure how to execute this script to generate the output. Do you have another script which makes use of the lookup function?

**Comment by aerickt** [comment]
This is a python dictionary. You'll have to install the plover-python-dictionary from the plugins manager. Then load `emily-symbols.py` as a dictionary after restarting Plover.

**Comment by Georift** [comment]
So I found my problem, it seem silly now but was not using the Plover python dict
