### ISSUE TITLE
My plover complained about the json file: backslashes are not escaped

### ISSUE THREAD

**Issue by cniekel** [EPLHREU/emily-symbols#5]
Hi!

I tried to install the json file into plover (just got the most recent plover installation for windows), and I got parse errors for the various entries with backslashes.

Apparently, the json parser doesn't understand `\{`, so I had to double the backslashes into `\\{` (and the same for 2, 3, 4 backslashes).

I thought I'd edit the python script and rerun it, but the python script needs to be imported somewhere, running it doesn't do anything.

**Comment by cniekel** [comment]
Hmm, my fix doesn't actually type a backslash now:
```

{^\^}:
   SPWHRAERB
{^}\{^}:
   SKWH-FB
```
The one from another dictionary does work. I should learn what the plover curly stuff all do.

**Comment by aerickt** [comment]
Hi, the python file is actually a python dictionary. You have to install the `plover-python-dictionary` plugin with the plugins manager and then add `emily-symbols.py` as any other Plover dictionary. You can use this as a workaround if the json dictionary doesn't work.

**Comment by EPLHREU** [comment]
Thanks for this, I just hastily threw together the json file as output from a generation script i wrote, so yeah - none of it would be escaped properly. 
As aerickt said, the python version of the dictionary is 100% what you should use with the python-dictionary plugin. 
Perhaps I should move the .json file off into `stuff/` to make it less obvious. 
If you have any issues installing the python-dictionary plugin then just message back and let me know, and i'll happily help you out :) 

But yes, I will escape everything properly for the .json and keep it around as a backup for when python dictionaries can't be used!

**Comment by cniekel** [comment]
I got it working. Thanks!
