### ISSUE TITLE
 Escaping \ in .json

### ISSUE THREAD

**Issue by robert-winkler** [EPLHREU/emily-symbols#6]
Great dictionary! I just experienced some problems with the .json version on Debian Buster and Ubuntu 20.04.
The \ needed to be changed to \\.
The Python dictionary works fine, but is not compatible with the CLI version of Plover.
Best, Robert

**Comment by EPLHREU** [comment]
Thanks for the issue, i'm glad you like it :) 

Loading up the .json version of the dictionary on my machine running macOS Catalina 10.15.7 I am unable to recreate this. For example here is a steno session with output and the strokes made using the .json file testing all possible variations of "\\" strokes:

```
cat\cat\\cat\\\cat\\\\cat
cat \cat \\cat \\\cat \\\\cat
cat\ cat\\ cat\\\ cat\\\\ cat
cat \ cat \\ cat \\\ cat \\\\ cat
cat\Cat\\Cat\\\Cat\\\\Cat
cat \Cat \\Cat \\\Cat \\\\Cat
cat\ Cat\\ Cat\\\ Cat\\\\ Cat
cat \ Cat \\ Cat \\\ Cat \\\\ Cat
```
`KAT/SKWH-FB/KAT/SKWH-FBS/KAT/SKWHFB-T/KAT/SKWH-FBTS/KAT`
`KAT/SKWHAFB/KAT/SKWHAFBS/KAT/SKWHFBAT/KAT/SKWHAFBTS/KAT`
`KAT/SKWHOFB/KAT/SKWHOFBS/KAT/SKWHFBOT/KAT/SKWHOFBTS/KAT`
`KAT/SKWHAOFB/KAT/SKWHAOFBS/KAT/SKWHFBAOT/KAT/SKWHAOFBTS/KAT`
`KAT/SKWH*FB/KAT/SKWH*FBS/KAT/SKWHFB*T/KAT/SKWH*FBTS/KAT`
`KAT/SKWHA*FB/KAT/SKWHA*FBS/KAT/SKWHFBA*T/KAT/SKWHA*FBTS/KAT`
`KAT/SKWHO*FB/KAT/SKWHO*FBS/KAT/SKWHFBO*T/KAT/SKWHO*FBTS/KAT`
`KAT/SKWHAO*FB/KAT/SKWHAO*FBS/KAT/SKWHFBAO*T/KAT/SKWHAO*FBTS/KAT`

Throughout this session I received no errors via plover, with the outputted text being directly typed from plover itself. 
Would you be able to provide a similar example session to show how "\\" is not working for you?

Additionally, can you check you are using the most recent version of the .json file, as a while ago I did remove an old and incorrect version from the root directory and add in the current, correct version into `/stuff` where it now lies.

```
:- md5 emily-symbols.json
MD5 (emily-symbols.json) = 8ba45a404c0cdf55e52ff02940b7e92f
```

```
:- git status emily-symbols.json
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
```

**Comment by robert-winkler** [comment]
Hi, I used the version from may 5th (direct download without git), and the JSON dictionary did not even load into Plover (escape errors).

Now, after updating the dictionaries with git, the JSON works!
